### PR TITLE
Update cached method callbacks

### PR DESCRIPTION
**Pull request by Tommatheussen**
This change puts the `.cached` method in line with the `.then` or `.success` methods.
If useLegacyPromiseExtensions is set to false (needs to be explicitly set right now), the cached method will be returned the same way as the then method. Namely in the format
`function (response, itemCache) {}`

If useLegacyPromiseExtensions is enabled (by default), the cached method still returns the same as before, in the same format as the success method.

### CODE REVIEW

**Comment by shaungrady** [comment]
Thanks so much for the PR! Your contribution is greatly appreciated. I'm a little hesitant, though. It feels weird to change the argument structure of a callback based on a seemingly unrelated flag. I like the idea of keeping it in line with `.then`, but it feels like it's an unconventional behavior that is difficult to communicate to users and could confuse them when that flag gets switched to false. I'd love to hear your thoughts on it.

**Comment by Tommatheussen** [comment]
Well, I wouldn't say it's an entirely unrelated flag, but I understand your concern.
The useLegacyExtensions is set the `true` by default, according to the docs (https://code.angularjs.org/1.5.8/docs/api/ng/provider/$httpProvider#useLegacyPromiseExtensions).
So in general nothing should change unless users explicitly set the flag to false.
In my understanding this flag is 'only' used when developers want to make sure they are in line with the latest functions, and not use legacy ones). If this is the case, it's probably also more convenient for them to be able to process the `.cached` information the same way as the `.then` information (same function even).

Perhaps it would be better to set this flag in the cache configuration (during config phase)?
Of perhaps even a combination, that `useLegacyExtensions` as well as `cacheConfigurationFlag` need to be correct before the callback gets changed?

**Comment by shaungrady** [comment]
I like your argument about being able to use the same function. But if the `useLegacyExtensions` flag is flipped, it becomes a breaking change that doesn't throw an exception. In Angular, the `success` and `error` methods go away altogether, and it feels appropriate that, perhaps, `cached` should go away, too. But if that happened, how would you use the callback?

Maybe it makes sense to introduce a new method that follows the argument structure of the `then` callbacks. Maybe something like `ifCached`, to follow a similar naming scheme to `then`?

``` javascript
// `useLegacyExtensions` === true
var promise = $http
  .get()
  .then(success, error)
  .ifCached( cb(response, itemCache) )
  .cached( cb(data, 'cached', undefined, config, itemCache) )

```

``` javascript
// `useLegacyExtensions` === false
// `.cached` method throws `$http:legacy` error

var promise = $http
  .get()
  .then(success, error)
  .ifCached( cb(response, itemCache) )
```

This way, `cached` and `ifCached` can have different callback argument structures, and can both exist at the same time while `useLegacyExtensions` is `true`. But when `false`, `cached` can go away with `success` and `error`, as does the old callback argument structure. And the `$http:legacy` would get thrown when trying to use `cached`, so devs _know_ that they have to use the new method with the new callback.

**Comment by Tommatheussen** [comment]
I like that, the idea of having the `cached` method go away completely is nice and inline with the `success` and `error` deprecation.
It will be a much nicer solution than what I've done here, since it won't introduce any breaking changes when the flag gets flipped.

I'll close this one, and see if I can find the time (tomorrow or this weekend) to create the new method.

**Comment by shaungrady** [comment]
👍 Thanks, Tom!

**Comment by shaungrady** [comment]
Something else I wanted to mention, you only need to make changes in `src/`—it gets packaged up and spit out into  `lib/` and `release/` as part of the versioning script.

**Comment by Tommatheussen** [comment]
Ah ok, good that you mention it, currently used the packaged script to test it in a project, but I won't add it to the commits next time.

**Comment by shaungrady** [comment]
You can use `npm run build` or `npm run build-umd` to build the CommonJS or UMD bundles, respectively.

**Pull request closed without merging**
